# Plugin configuration
# Documentation:
#   https://prow.istio.io/plugins
#   https://github.com/kubernetes/test-infra/tree/master/prow/plugins#readme
#   https://github.com/kubernetes/test-infra/blob/master/prow/plugins/config.go
triggers:
- repos:
  - istio
  - istio-ecosystem
  - istio-releases
  trusted_org: istio

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    boskos/resources.yaml:
      name: boskos-config
      namespace: boskos
    boskos/configs.yaml:
      name: mason-config
      namespace: boskos
    prow/cluster/jobs/**/*.yaml:
      name: job-config

slack:
  mergewarnings:
  - repos:
    - istio/test-infra
    channels:
    - test-and-release
    whitelist:
    - istio-testing

lgtm:
- repos:
  - istio
  - istio-ecosystem
  - istio-releases
  review_acts_as_lgtm: true
  trusted_team_for_sticky_lgtm: "Istio Hackers"

approve:
- repos:
  - istio
  - istio-ecosystem
  - istio-releases
  implicit_self_approve: true

plugins:
  istio:
  - approve
  - assign
  - blunderbuss
  - config-updater
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - verify-owners
  - wip

  istio/test-infra: # TODO(fejta): enable these at org level
  - shrug
  - skip
  - yuks

  istio-releases:
  - approve
  - assign
  - blunderbuss
  - config-updater
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - verify-owners
  - wip

  istio-ecosystem:
  - approve
  - assign
  - blunderbuss
  - config-updater
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - verify-owners
  - wip

external_plugins:
  istio:
  - name: needs-rebase
    events:
      - pull_request
  istio-releases:
  - name: needs-rebase
    events:
      - pull_request
  istio-ecosystem:
  - name: needs-rebase
    events:
      - pull_request
